# Generated by Django 4.2 on 2023-04-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_category2_cat_category3_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category2',
            old_name='cat',
            new_name='cat1',
        ),
        migrations.RenameField(
            model_name='category3',
            old_name='cat',
            new_name='cat2',
        ),
    ]
